version: "3"
services:
  activemq:
    image: rmohr/activemq:5.15.6
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./conf:/opt/apache-activemq-5.15.6/conf
      - ./data:/opt/apache-activemq-5.15.6/data