version: "3.9"
services:
  activemq:
    image: rmohr/activemq:5.15.6
    ports:
      - 61616:61616
      - 8161:8161
    # volumes:
    #   - ./conf:opt/activemq/conf
    #   - ./data:opt/activemq/data